version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU
build:
  verbosity: minimal
after_build:
- cmd: 7z a htaccess2Webconfig.zip %APPVEYOR_BUILD_FOLDER%\htaccess2Webconfig\bin\Release\*.*
artifacts:
- path: htaccess2Webconfig.zip
  name: htaccess2Webconfig
deploy:
- provider: GitHub
  release: htaccess2Webconfig-v$(APPVEYOR_BUILD_VERSION)
  description: Release description
  auth_token:
    secure: sGvXHW8/VMYpZ9+X7/KMOGnYRnA+Opj0/wK20UjJZbFtDP22dxRsC7C+M44h702u
  artifact: /.*\.zip/
  on:
    branch: master
